In [5]:
import numpy as np
np

#create arrays
#useful functions
.zeros
.ones
.full
.arange
.linspace


np.zeros(5)


array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
a[2]

NameError: name 'a' is not defined

In [9]:
a = np.full(10,3)
a

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [10]:
a[2]

np.int64(3)

In [14]:
np.arange(4, 10)


array([4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [15]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [17]:
#multidimensional arrays
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
n = np.array([
        [1,2,3],
         [4,5,6,],
         [7,8,9]
         ])

In [24]:
n[2]

array([7, 8, 9])

In [25]:
n[0,1]

np.int64(2)

In [26]:
n[0,1] = 20

In [30]:
n[0]


array([ 1, 20,  3])

In [32]:
n[:,1]


array([20,  5,  8])

In [33]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [38]:
#to have same set for each run:
np.random.seed(2)
#pseudo-random - different set each run
np.random.rand(5,2)
#normal distribution:
np.random.randn(5,2)


array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [40]:
#defining the parameters for the matrix:
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [42]:
#adding operations to arrays
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
a + 1

array([1, 2, 3, 4, 5])

In [46]:
#chain
b = (10 + (a * 2)) ** 2

In [47]:
#work with multiple arrays
a + b

array([100, 145, 198, 259, 328])

In [48]:
#comparison operations
a >=2

array([False, False,  True,  True,  True])

In [49]:
a

array([0, 1, 2, 3, 4])

In [50]:
b

array([100, 144, 196, 256, 324])

In [51]:
#returns boolean array
a > b

array([False, False, False, False, False])

In [52]:
#this returns elements for which it is true
#[]
a[a > b]

array([], dtype=int64)

In [55]:
a.min()
a.max()
a.mean()
a.std()
a.mode()
a.sum()

<function ndarray.mean>